apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  OTP_SECRET: {{ randAlphaNum 42 | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 42 | b64enc | quote }}
  PAPERCLIP_SECRET: {{ randAlphaNum 42 | b64enc | quote }}
  tls.crt: {{ .Values.tlsCrt | b64enc }}
  tls.key: {{ .Values.tlsKey | b64enc }}
